[package]
name = "mandelbrotFPGA"
version = "0.0.0"
description = "host software for mandelbrotFPGA"
edition = "2021"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"

[dependencies]
tapasco = { path = "runtime/libtapasco" }
